-- Active: 1729524770416@@127.0.0.1@5430@postgres@hospital
create table specialization (
    id int primary key generated by default as identity ,
    name varchar(100)
);

create table department (
    id int primary key generated by default as identity,
    specialization_id int references specialization("id") on delete set null ,
    name varchar(50) not null ,
    capacity int not null
);