drop type payment_way cascade ;

alter table payments drop column payment_for_what;

drop type payment_type cascade ;
create type payment_type as enum ('month', 'penalty');
alter table payments_schedule add column payment_for_what payment_type not null default 'month';

alter table payments_schedule add column id bigint primary key generated by default as identity ;

-- alter table payments drop column credit_id;
alter table payments add column payment_schedule_id bigint references payments_schedule("id");
alter table payments add column id bigint primary key generated by default as identity ;

/*
хочется хранить размер платежа погашающего только основной долг в таблице payments, потому что от этого запросы будут проще
но тогда придется хранить в них сумму платежа, а еще придется хранить, что именно этот платеж гасил основной долг
размер в платежах - лишние данные, они же есть в расписании, но они мне нужны для погашения основного долга

допустим, я бы сделал отдельную таблицу платежей, которая хранила бы только погашение основного долга, тогда бы в запросах
пришлось бы еще и ее суммировать
*/

create table main_debt_payment (
    payment_id bigint not null references payments("id") ,
    credit_id bigint not null references credits("id") ,
    primary key (payment_id, credit_id)
);

