-- добавить проверку на то, что человек имеет в таблице staff
drop table if exists staff_change;
create table staff_change (
    id int primary key generated by default as identity ,
    staff_id uuid not null references person("id") ,
    type int not null
);
truncate table staff_change;

drop table if exists duty_schedule;
create table duty_schedule (
    int uuid primary key ,
    doctor_id uuid not null references doctor("id") ,
    department_id uuid not null references department("id") ,
    start_time timestamp not null ,
    end_time timestamp not null
);
truncate table duty_schedule cascade;

