create or replace function check_staff_exist()
    returns trigger as $$
declare
    staffIsExist boolean;
begin
    select exists(select * from staff where id = NEW.id) into staffIsExist;

    if not staffIsExist then
        raise exception 'this staff does not exist';
    end if;

    return NEW;
end
$$ language plpgsql;

drop table if exists staff_change;
create table staff_change (
    id int primary key generated by default as identity ,
    staff_id uuid not null references staff("id") on delete cascade ,
    type int not null
);
truncate table staff_change;

create trigger staff_exist before insert on staff_change
    for each ROW execute function check_staff_exist();

drop table if exists duty_schedule;
create table duty_schedule (
    int uuid primary key ,
    doctor_id uuid not null references doctor("id") on delete cascade ,
    department_id uuid not null references department("id") on delete cascade ,
    start_time timestamp not null ,
    end_time timestamp not null
);
truncate table duty_schedule cascade;

