drop schema if exists public cascade ;
create schema public;

drop table if exists person cascade;
create table person (
    id int primary key generated by default as identity ,
    name varchar(50) not null ,
    second_name varchar(50) not null ,
    phone varchar(11) unique not null
);
truncate table person cascade;

drop table if exists passport cascade;
create table passport (
    person_id int primary key references person("id") on delete cascade ,
    series int not null ,
    number int not null
);
truncate passport cascade;

drop table if exists polis cascade;
create table polis (
    person_id int primary key references person("id") on delete cascade ,
    number int unique not null
);
truncate polis cascade;