drop table if exists staff cascade ;
create table staff (
    id uuid primary key default gen_random_uuid() ,
    salary int check ( salary > 0 ) ,
    person_id uuid references person("id")
);
truncate table staff cascade ;

drop table if exists staff_change;
create table staff_change (
    id int primary key generated by default as identity ,
    staff_id uuid not null references staff("id") on delete cascade ,
    type int not null
);
truncate table staff_change;

drop table if exists department cascade;
create table department (
    id uuid primary key default gen_random_uuid(),
    name varchar(50) not null ,
    number int not null ,
    capacity int not null
);
truncate department cascade;
