drop table if exists staff_change;
create table staff_change (
    id int primary key generated by default as identity ,
    staff_id int not null references staff("id") on delete cascade ,
    change_time timestamp not null
)
truncate table staff_change cascade;



drop table if exists staff_change_department cascade;
create table staff_change_department (
    id int primary key generated by default as identity ,
    was int references department("id") on delete cascade ,
    became int references department("id") on delete cascade ,
    patient_change_id int references staff_change("id")
);
truncate table staff_change_department cascade;