drop table if exists person cascade;
create table person (
    id int primary key generated by default as identity ,
    name varchar(50) not null ,
    second_name varchar(50) not null ,
    phone varchar(11) unique not null
);
truncate table person cascade;

drop table if exists doctor;
create table doctor (
    id int primary key references person("id") ,
    department int not null
);
truncate table doctor cascade;

drop table if exists patient;
create table patient (
  id int primary key references person("id")
--   id time
);
truncate table patient cascade;

drop table if exists passport cascade;
create table passport (
    person_id int primary key references person("id") ,
    series int not null ,
    number int not null
);
drop table if exists passport cascade;

drop table if exists polis cascade;
create table polis (
    person_id int primary key references person("id") ,
    number int unique not null
);
drop table if exists polis cascade;