create type credit_type as enum ('t1', 't2', 't3', 't4', 't5');
create table credit_tariff (
    id int primary key generated by default as identity ,
    type credit_type not null ,
    initial_amount int not null check ( initial_amount > 0 ),
    final_amount int not null check ( initial_amount > 0 ) ,
    payment_period interval not null ,
    credit_rate int not null check ( credit_rate > 0 )
);

/*create type deposit_type as enum ('t1', 't2', 't3', 't4', 't5');
create table deposit (
    id int primary key generated by default as identity ,
    type deposit_type not null ,
    deposit_rate int not null check ( deposit_rate > 0 )
);*/
