
create table person (
    id int primary key generated by default as identity ,
    name varchar(50) not null ,
    second_name varchar(50) not null ,
    phone varchar(11) unique not null
);


create table passport (
    person_id int primary key references person("id") on delete cascade ,
    series int not null check ( series >= 0 and series <= 9999 ),
    number int not null check ( number >= 0 and number <= 999999 ),
    constraint passport_unique unique (series, number)
);
