create type staff_changes as enum ( 'SALARY', 'POSITION', 'DEPARTMENT' ) ;

create table staff_change (
    id int primary key generated by default as identity ,
    staff_id int not null references staff("id") on delete cascade ,
    change_field staff_changes not null ,
    before varchar(50),
    after varchar(50) not null ,
    change_time timestamp not null
);
create index staff_change_index on staff_change using btree(staff_id);