create type patient_status_type as enum ('HEALTHY', 'OUT_TREATMENT', 'TREATMENT_IN_ANOTHER_PLACE');

create table patient (
    id int primary key generated by default as identity ,
    coming_time timestamp not null ,
    release_time timestamp,
    doctor_id int references doctor("staff_id") on delete set null ,
    status patient_status_type not null ,
    person_id int references person("id") ,
    constraint patient_not_equals_doctor check ( patient.person_id != patient.doctor_id )
);
alter table patient
    alter column coming_time type timestamp with time zone using coming_time::timestamp without time zone;
alter table patient
    alter column release_time type timestamp without time zone using release_time::timestamp without time zone;

create table polis (
    patient_id int primary key references person("id") ,
    number int8 unique not null check ( number > 0 and number < 9999999999999999 )
);

create table disease (
    id int primary key generated by default as identity ,
    patient_id int references patient("id") on delete cascade ,
    name varchar(100) ,
    installation_time timestamp not null ,
    doctor_id int references doctor("staff_id") ,
    is_relevant bool not null
);
create index disease_index on disease using btree (patient_id);


create table patient_change (
    id int primary key generated by default as identity ,
    patient_id int references patient("id") on delete cascade ,
    change_field staff_changes not null ,
    before varchar(50) not null,
    after varchar(50) not null ,
    change_time timestamp not null
);
create index patient_change_index on patient_change using btree (patient_id);