create table patient (
    id int generated by default as identity primary key ,
    passport_series varchar(4) check ( passport_number like '\d{4}' ),
    passport_number varchar(6) check ( passport_number like '\d{6}' ),
    polis_number varchar(16) unique check ( polis_number like '\d{16}' ),

    name varchar(50) not null ,
    second_name varchar(50) not null ,
    phone varchar(11) unique check ( phone like '\d{11}' ) ,

    doctor_id int references doctor("staff_id") on delete set null ,
    constraint patient_not_equals_doctor check ( id != patient.doctor_id )
);
-- alter table patient
--     alter column coming_time type timestamp with time zone using coming_time::timestamp without time zone;
-- alter table patient
--     alter column release_time type timestamp without time zone using release_time::timestamp without time zone;

create table disease (
    id int primary key generated by default as identity ,
    patient_id int references patient("id") on delete cascade ,
    name varchar(100) ,
    installation_time timestamp not null ,
    doctor_id int references doctor("staff_id") ,
    is_relevant bool not null
);
create index disease_index on disease using btree (patient_id);

create table patient_change (
    id int primary key generated by default as identity ,
    patient_id int references patient("id") on delete cascade ,
    change_field staff_changes not null ,
    before varchar(50) not null,
    after varchar(50) not null ,
    change_time timestamp not null
);
create index patient_change_index on patient_change using btree (patient_id);