drop table if exists employees_managers;
drop table if exists employees;
create table employees (
    id int primary key generated by default as identity ,
    name varchar(50) not null ,
    position_id int references positions("id") on delete set null,
    manager_id int default null,

    foreign key (manager_id) references employees("id")
        DEFERRABLE INITIALLY IMMEDIATE
)