alter table payments drop column payment_for_what;
drop type payment_type cascade ;
create type payment_type as enum ('month', 'penalty');
alter table payments_schedule add column payment_for_what payment_type not null default 'month';

alter table payments_schedule add column id bigint primary key generated by default as identity ;
alter table payments add column payments_schedule_id bigint references payments_schedule("id") ;
