create type credit_type as enum ('t1', 't2', 't3', 't4', 't5');
create table credit_tariffs (
    id int primary key generated by default as identity ,
    type credit_type not null ,
    initial_amount numeric(15, 2) not null check ( initial_amount > 0 ),
    final_amount numeric(15, 2) not null check ( initial_amount > 0 ) ,
    payment_period interval not null ,
    credit_percent int not null check ( credit_percent > 0 )
);

create table credit_tariff_client (
    client_id int references clients("id") on delete cascade ,
    credit_tariff_id int references credit_tariffs("id") on delete cascade ,
    primary key (client_id, credit_tariff_id)
);
