services:
  postgres:
    container_name: postgres
    image: postgres:16.4
    hostname: database
    environment:
      - POSTGRES_DB=databaseNSU
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5430:5432