create table stations (
    id int primary key generated by default as identity,
    name varchar(100) not null
);

create table routes (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    departure_point int references stations(id) not null,
    arrival_point int references stations(id) not null
);

create type trains_category as enum('c1', 'c2', 'c3');
create table trains (
    id int primary key generated by default as identity,
    category trains_category not null default 'c1'::trains_category,
    header_station int references stations(id)
);

create table threads (
    id int primary key generated by default as identity,
    route int references routes(id) not null,
    train int references trains(id) not null,
    date date not null default current_date
);

create table threads_info (
    id int primary key generated by default as identity,
    thread int references threads(id),
    station int references stations(id),
    station_number_in_thread int not null,
    constraint route_station unique (thread, station),
    arrival_time time,
    departure_time time,
    distance int not null default (random() * 100)
);

create table delay (
    thread_info int references threads_info(id) not null,
    arrival_delay int not null default 0,
    departure_delay int not null default 0
);

create type railroad_cars_category as enum('c1', 'c2', 'c3');
create table railroad_cars (
    id int primary key generated by default as identity,
    category railroad_cars_category not null default 'c3'::railroad_cars_category,
    schema jsonb
);

create table railroad_cars_train (
    id int primary key generated by default as identity,
    train int references trains(id) not null,
    railroad_car int references railroad_cars(id) not null,
--     primary key (train, railroad_car),
    constraint railroad_car_in_train unique (train, railroad_car),
    number int not null default 0
);

create table passengers (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    passport_series int not null,
    passport_number int not null,
    constraint passengers_passport unique (passport_number, passport_series)
);

create table booking (
    id int primary key generated by default as identity,
    passenger int references passengers(id) not null,
    time timestamp not null default current_timestamp
);

create table railroads_cars_booking (
    id int primary key generated by default as identity,
    railroad_car int references railroad_cars_train(id) not null,
    place int not null,
    departure_point int references threads_info(id) not null,
    arrival_point int references threads_info(id) not null check ( departure_point != arrival_point ),
    booking_info int references booking(id) not null
);

create type staff_position as enum ('p1', 'p2', 'p3');
create table staff (
    id int primary key generated by default as identity ,
    name varchar(50) not null,
    passport_series int not null,
    passport_number int not null,
    constraint staff_passport unique (passport_number, passport_series),
    position staff_position default 'p1'::staff_position,
    manager_id int default null,
    foreign key (manager_id) references staff("id") deferrable initially immediate
);

create table train_crew (
    employee int references staff(id) not null,
    train int references trains(id) not null,
    setup_time timestamp not null default current_timestamp,
    remove_time timestamp
);
