create table routes (
    id int primary key generated by default as identity,
    name varchar(100) not null
);

create table stations (
    id int primary key generated by default as identity,
    name varchar(100) not null
);

create table stations_routes (
    route int references routes(id),
    station int references stations(id),
    arrival_time timestamp default current_timestamp,
    departure_time timestamp default current_timestamp,
    primary key (route, station)
);

create table trains (
    id int primary key generated by default as identity,
    category varchar(100) not null,
    header_station int references stations(id)
);

create table railroad_cars (
    id int primary key generated by default as identity,
    category varchar(100) not null ,
    train int references trains(id),
    number int primary key not null
);

create table booking (
    id int primary key generated by default as identity,
    train int references trains(id) not null,
    railroad_car int references railroad_cars(id) not null,
    from
)
