create table routes (
    id int primary key generated by default as identity,
    name varchar(100) not null
);

create table stations (
    id int primary key generated by default as identity,
    name varchar(100) not null
);

create table schedules (
    route int references routes(id),
    station int references stations(id),
    primary key (route, station),
    arrival_time time,
    departure_time time,
    distance int not null default (random() * 100)
);

create table trains (
    id int primary key generated by default as identity,
    category varchar(100) not null,
    header_station int references stations(id)
);

create type railroad_cars_category as enum('c1', 'c2', 'c3');
create table railroad_cars (
    id int primary key generated by default as identity,
    category railroad_cars_category not null default 'c3'::railroad_cars_category,
    train int references trains(id),
    number int not null default 0
);

create table trains_routes (
    id int primary key generated by default as identity,
    route int references routes(id) not null,
    train int references trains(id) not null,
    arrival_time timestamp,
    departure_time timestamp
);

create table passengers (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    passport_series int not null,
    passport_number int not null,
    constraint passengers_passport unique (passport_number, passport_series)
);

create table booking (
    id int primary key generated by default as identity,
    railroad_car int references railroad_cars(id) not null,
    trip int references trains_routes(id) not null,
    passenger int references passengers(id) not null
);

create type staff_position as enum ('p1', 'p2', 'p3');
create table staff (
    id int primary key generated by default as identity ,
    name varchar(50) not null,
    passport_series int not null,
    passport_number int not null,
    constraint staff_passport unique (passport_number, passport_series),
    position staff_position default 'p1'::staff_position,
    manager_id int default null,
    foreign key (manager_id) references staff("id") deferrable initially immediate
);
