create table stations (
    id int primary key generated by default as identity,
    name varchar(100) not null
);

create table routes (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    departure_point int references stations(id) not null,
    arrival_point int references stations(id) not null
);

create type trains_category as enum('c1', 'c2', 'c3');
create table trains (
    id int primary key generated by default as identity,
    category trains_category not null default 'c1'::trains_category,
    header_station int references stations(id)
);

create table railroad_cars_category (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    schema jsonb
);
insert into railroad_cars_category (name) values ('c1'), ('c2'), ('c3');

create table routes_structure (
    id int primary key generated by default as identity,
    route_id int references routes(id) not null,
    station_id int references stations(id) not null,
    constraint route_station unique (route_id, station_id),
    station_number_in_route int not null,
    distance int not null
);

create table trains_on_route (
    train_id int references trains(id),
    route_id int references routes(id),
    primary key (train_id, route_id),
    setup_time timestamp not null default current_date,
    remove_time timestamp
);

create table railroad_cars (
    id int primary key generated by default as identity,
    train_id int not null,
    route_id int not null,
    foreign key (train_id, route_id) references trains_on_route(train_id, route_id),
    number_in_train int not null default 0,
    category_id int references railroad_cars_category(id)
);

create table schedule (
    id int primary key generated by default as identity,
    route_structure_id int references routes_structure(id) not null,
    departure_time timestamp,
    arrival_time timestamp
);

create table delay (
    schedule_record int references schedule(id) not null,
    arrival_delay int not null default 0,
    departure_delay int not null default 0
);

create table passengers (
    id int primary key generated by default as identity,
    name varchar(100) not null,
    passport_series int not null,
    passport_number int not null,
    constraint passengers_passport unique (passport_number, passport_series)
);

create table booking (
    id int primary key generated by default as identity,
    passenger_id int references passengers(id) not null,
    time timestamp not null default current_timestamp
);

create table railroads_cars_booking (
    id int primary key generated by default as identity,
    railroad_car_id int references railroad_cars(id) not null,
    place int not null,
    departure_point int references schedule(id) not null,
    arrival_point int references schedule(id) not null check ( departure_point != arrival_point ),
    booking_record int references booking(id) not null
);

create type staff_position as enum ('p1', 'p2', 'p3');
create table staff (
    id int primary key generated by default as identity ,
    name varchar(50) not null,
    passport_series int not null,
    passport_number int not null,
    constraint staff_passport unique (passport_number, passport_series),
    position staff_position default 'p1'::staff_position,
    manager_id int default null,
    foreign key (manager_id) references staff("id") deferrable initially immediate
);

create table train_crew (
    employee_id int references staff(id) not null,
    train_id int references trains(id) not null,
    setup_time timestamp not null default current_timestamp,
    remove_time timestamp
);
