create type climate_type as enum ('CL1', 'CL2', 'CL3', 'CL4');
create type continent_type as enum ('CO1', 'CO2', 'CO3', 'CO4', 'CO5', 'CO6');
create table habitat (
    id int primary key generated by default as identity ,
    name varchar(100) not null ,
    climate climate_type not null ,
    continent continent_type not null
);

create type food_type as enum ('PREDATOR', 'HERBIVORE', 'OMNIVOROUS');
create table animal_type (
    id int primary key generated by default as identity ,
    name varchar(100) not null ,
    food_type food_type not null ,
    habitat int references habitat("id") on delete set null
);

create table cage (
    id int primary key generated by default as identity ,
    length int not null check ( length > 0 ) ,
    width int not null check ( width > 0 ) ,
    height int not null check ( height > 0 ) ,
    place varchar(100) not null /* ??? */
);

create table animal (
    id int primary key generated by default as identity ,
    animal_type int not null references animal_type("id") on delete set null,
    cage int not null references cage("id") on delete set null,
    name varchar(100) not null ,
    weight int not null check ( weight > 0) ,
    length int not null check ( length > 0 ) ,
    coming_time timestamp with time zone not null default current_timestamp
)