create table payments_schedule (
    id bigint primary key generated by default as identity ,
    credit_id bigint not null references credits("id") on delete cascade ,
    amount numeric(15, 2) not null check ( amount > 0 ) ,
    deadline timestamp with time zone not null,
    is_paid boolean default false
);

create table payments (
    amount numeric(15, 2) not null check ( amount > 0 ) ,
    commission decimal(15, 2) not null check ( commission >= 0 ) default 0 ,
    time timestamp with time zone not null default current_timestamp ,
    credit_id bigint not null references credits("id") on delete set null ,
    payments_schedule bigint references payments_schedule("id")
);